[package]
name = "raft"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13"
protobuf-build = { path = "../protobuf-build" }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.12"
