# Orchestration Parameters
N = 10
START_PORT = 5000
IMAGE = "raft-node"
REQUEST_INTERVAL_TIME = 0.5
WRITE_PROBABILITY = 0.5
N_REQUESTS = 20

# Benchmark Parameters
BENCHMARK_DURATION = 30
FAULT_INJECTION_ENABLED = true
LEADER_KILL_PROBABILITY = 0.5
