# Orchestration Parameters
N = 3
START_PORT = 8000
IMAGE = "zab-node"
REQUEST_INTERVAL_TIME = 0.5
WRITE_PROBABILITY = 0.50

# Benchmark Parameters
BENCHMARK_DURATION = 60
FAULT_INJECTION_ENABLED = true
LEADER_KILL_PROBABILITY = 0.25